implement the functionality that allows a user get all orders
andrewinsoul/Fast-Food-Fast pull request #3
Opened 2018-09-17 00:10 UTC by andrewinsoul

### WHAT DOES THIS PR DO?
Have the get all orders endpoint working in Fast Food REST API

### DESCRIPTION OF TASK TO BE COMPLETED
- Set up express server
- Have GET /orders working

### HOW SHOULD THIS BE MANUALLY TESTED?
After cloning the repo, cd into it and RUN npm start, using postman, test the endpoint GET /orders
It should return status 200 with an empty array as no orders are yet added.

###WHAT ARE THE RELEVANT PIVOTAL TRACKER STORIES?
#160539515

2018-09-17 11:19 UTC, OsayamenOsaretin commented
The description of tasks to be completed should a description of the tasks you took to "Have GET/ orders working". What steps did you take to get it working.

The headers in your PR description, e.g "Description of task to be completed" doesn't have to be in all caps.

Check that the markdown is appropriately formatted.

2018-09-17 11:32 UTC, OsayamenOsaretin commented
Your commit message doesn't follow the prescribed format. Please check [this](https://github.com/andela/project-jiayou-cfh/wiki/Git-Branch-Naming-Convention), and correct accordingly

2018-09-17 13:18 UTC, dogoyaro requested changes

2018-09-17 13:18 UTC, OsayamenOsaretin commented on server/models/order.js
> +export default orders;
The default export should be the same name as the file. Change `order.js` to `orders.js`.

2018-09-17 13:18 UTC, OsayamenOsaretin commented on server/controllers/order.js
> +class OrderClass {
`class Order` is a superior name to `class OrderClass`

2018-09-17 13:18 UTC, OsayamenOsaretin commented on server/models/order.js
> +const orders = [];
Are you certain that an array is the best data structure to store orders?

2018-09-17 13:18 UTC, OsayamenOsaretin commented on .eslintrc.js
>  };
I think you need a newline at the end of this file.

2018-09-17 13:25 UTC, andrewinsoul commented on server/models/order.js
> +const orders = [];
Yes, it has method that allows for easy retrieval of an item and also update an item. Methods like push, findIndex, find and other array methods makes me think it's the suitable data structure for the job

2018-09-17 17:45 UTC, andrewinsoul commented
si i

2018-09-18 10:35 UTC, OsayamenOsaretin commented on server/models/order.js
> +export default orders;
@andrewinsoul. Please address this issue so we can merge this PR.

2018-09-18 22:40 UTC, merged